name: minibatch
channels:
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_4
  - libffi=3.4.6=h2dba641_1
  - libgcc=14.2.0=h767d61c_2
  - libgcc-ng=14.2.0=h69a702a_2
  - libgomp=14.2.0=h767d61c_2
  - liblzma=5.8.1=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_2
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.10.16=habfa6aa_2_cpython
  - readline=8.2=h8c095d6_2
  - setuptools=78.1.0=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
      - affine==2.4.0
      - aiobotocore==2.21.1
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.16
      - aioitertools==0.12.0
      - aiosignal==1.3.2
      - anndata==0.11.4
      - array-api-compat==1.11.2
      - asciitree==0.3.3
      - asttokens==3.0.0
      - async-timeout==5.0.1
      - attrs==25.3.0
      - botocore==1.37.1
      - cellcharter==0.3.4
      - certifi==2025.1.31
      - charset-normalizer==3.4.1
      - click==8.1.8
      - click-plugins==1.1.1
      - cligj==0.7.2
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - comm==0.2.2
      - contourpy==1.3.1
      - cycler==0.12.1
      - dask==2024.11.2
      - dask-expr==1.1.19
      - dask-image==2024.5.3
      - datashader==0.17.0
      - debugpy==1.8.13
      - decorator==5.2.1
      - distributed==2024.11.2
      - docrep==0.3.2
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fasteners==0.19
      - filelock==3.18.0
      - fonttools==4.57.0
      - frozenlist==1.5.0
      - fsspec==2025.3.2
      - geopandas==1.0.1
      - h5py==3.13.0
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.6.1
      - inflect==7.5.0
      - ipykernel==6.29.5
      - ipython==8.34.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - jmespath==1.0.1
      - joblib==1.4.2
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - kiwisolver==1.4.8
      - lazy-loader==0.4
      - legacy-api-wrap==1.4.1
      - lightning-utilities==0.14.3
      - llvmlite==0.44.0
      - locket==1.0.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.1
      - matplotlib-inline==0.1.7
      - matplotlib-scalebar==0.9.0
      - mdurl==0.1.2
      - more-itertools==10.6.0
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.3.2
      - multipledispatch==1.0.0
      - multiscale-spatial-image==2.0.2
      - natsort==8.4.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - numba==0.61.0
      - numcodecs==0.13.1
      - numpy==1.26.4
      - ome-zarr==0.10.3
      - omnipath==1.0.9
      - openpyxl==3.1.5
      - packaging==24.2
      - pandas==2.2.3
      - param==2.2.0
      - parso==0.8.4
      - partd==1.4.2
      - patsy==1.0.1
      - pexpect==4.9.0
      - pillow==11.1.0
      - pims==0.7
      - platformdirs==4.3.7
      - pooch==1.8.2
      - prompt-toolkit==3.0.50
      - propcache==0.3.1
      - psutil==7.0.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.1
      - pyct==0.5.0
      - pygments==2.19.1
      - pynndescent==0.5.13
      - pyogrio==0.10.0
      - pyparsing==3.2.3
      - pyproj==3.7.1
      - python-dateutil==2.9.0.post0
      - pytorch-lightning==2.5.1
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - rasterio==1.4.3
      - requests==2.32.3
      - rich==14.0.0
      - s3fs==2025.3.2
      - scanpy==1.11.1
      - scikit-image==0.25.2
      - scikit-learn==1.5.2
      - scipy==1.15.2
      - seaborn==0.13.2
      - session-info==1.0.0
      - session-info2==0.1.2
      - shapely==2.1.0
      - six==1.17.0
      - sknw==0.15
      - slicerator==1.1.0
      - sortedcontainers==2.4.0
      - spatial-image==1.2.1
      - spatialdata==0.3.0
      - spatialdata-plot==0.2.9
      - squidpy==1.6.5
      - stack-data==0.6.3
      - statsmodels==0.14.4
      - stdlib-list==0.11.1
      - sympy==1.13.3
      - tblib==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.3.30
      - toolz==1.0.0
      - torch==2.1.0+cu118
      - torch-cluster==1.6.3+pt21cu118
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2+pt21cu118
      - torch-sparse==0.6.18+pt21cu118
      - torch-spline-conv==1.2.2+pt21cu118
      - torchaudio==2.1.0+cu118
      - torchgmm==0.1.2
      - torchmetrics==1.7.0
      - torchvision==0.16.0+cu118
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - triton==2.1.0
      - typeguard==4.4.2
      - typing-extensions==4.13.1
      - tzdata==2025.2
      - umap-learn==0.5.7
      - urllib3==2.3.0
      - validators==0.34.0
      - wcwidth==0.2.13
      - wrapt==1.17.2
      - xarray==2024.11.0
      - xarray-dataclasses==1.9.1
      - xarray-schema==0.0.3
      - xarray-spatial==0.4.0
      - yarl==1.19.0
      - zarr==2.18.3
      - zict==3.0.0
      - zipp==3.21.0
prefix: /home/jeongbp/.conda/envs/minibatch
